# ansible playbook to setup desktop environment:
# - install packages: 
#    - aptitude
#    - firefox
#    - vlc
#    - gimp

# also run docker-install.yml playbook

- hosts: all
  become: true
  tasks:
    - name: Install desktop environment packages
      apt:
        name:
          - aptitude
          - firefox
          - vlc
          - gimp
          - git
          - curl
          - wget
          - htop
          - thunderbird
          - filezilla
          - neovim
        state: latest
        update_cache: true

    - name: Download Bitwarden client
      get_url:
        url: https://vault.bitwarden.com/download/?app=desktop&platform=linux
        dest: /tmp/bitwarden.deb

    - name: Install Bitwarden client
      apt:
        deb: /tmp/bitwarden.deb

    - name: Run docker-install.yml playbook
      import_tasks: docker-install.yml
